name: Android Test Apps Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container:

    runs-on: ubuntu-latest
    container: crazyuploader/android_sdk:latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run: |
        ./script.sh
